CREATE TABLE [dbo].[model]
(
	[id] INT NOT NULL PRIMARY KEY,
    [name] NVARCHAR(50) NOT NULL,
    [model] varbinary(max) NOT NULL,
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL, 
    CONSTRAINT [CK_model_name] UNIQUE ([name]), 
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[model_HISTORY], DATA_CONSISTENCY_CHECK=ON))
